openapi: 3.0.0
info:
  title: Book Management API
  version: 1.0.0
paths:
  /books:
    get:
      summary: Lấy danh sách các quyển sách
      responses:
        200:
          description: Trả về danh sách các quyển sách
    post:
      summary: Thêm sách mới
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        201:
          description: Sách được thêm thành công
components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        author:
          type: string
